###
# Build hdf5 dependencies and cache them in a combined directory.
###

name: netcdf_gcc_v4.9.2

on: 
  push:
    branches:  [ main, master] 
  
concurrency:  
  group: $${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

jobs:

  netcdf_gcc:

    runs-on: ubuntu-latest

    env:
      compiler: gcc
      CC: gcc
      FC: gfortran
      CXX: g++
      CLTAG: "8.6.0"
      ZLTAG: "1.3"
      H5TAG: "1.14.0"
      PNCTA: "1.12.3"
      NCTAG: "4.9.2"
      NFTAG: "4.6.0"
      
    steps:
      - uses: actions/checkout@v4
      - name: download pkgs
        run: |
          sudo apt update
          sudo apt install wget curl 
          
          source build_netcdff_serial.sh
          # download
          ls -l
      
      - name: System Dependencies
        run: |
          sudo apt install -y libaec-dev zlib1g-dev libjpeg-dev bzip2 m4 flex bison \
            automake autoconf cmake \
            libxml2-utils libzip-dev doxygen openssl tree
          sudo apt install libpsl-dev libcurl4-openssl-dev
          sudo apt install gfortran gcc g++
          # sudo apt install openmpi-bin libopenmpi-dev
          # sudo apt install pylint 
          gcc -v

      - name: cache curl and zlib
        id: cache-zlib
        uses: actions/cache@v4
        with:
          path: ~/environment/zlib
          key: Ubuntu2204_${{env.compiler}}_curl-v${{env.CLTAG}}_zlib-v${{env.ZLTAG}}
          save-always: true
      
      - name: build curl and zlib
        if: steps.cache-zlib.outputs.cache-hit != 'true'
        run: |
          source build_netcdff_serial.sh
          build_curl && build_zlib


      - name: cache hdf5
        id: cache-hdf5
        uses: actions/cache@v4
        with:
          path: ~/environment/hdf5
          key: Ubuntu2204_${{env.compiler}}_hdf5-v${{env.H5TAG}}
          save-always: true

      - name: build hdf5
        if: steps.cache-hdf5.outputs.cache-hit != 'true'
        run: |
          source build_netcdff_serial.sh
          build_hdf5
      
      - name: build netcdf and netcdff
        run: |
          source build_netcdff_serial.sh
          build_netcdf
          build_netcdff

      - name: list files
        run: |
          ls -l ~/environment
          
      - uses: actions/upload-artifact@v4
        with:
          name: Ubuntu2204_${{env.compiler}}_netcdf-v4.9.2
          path: |
            ~/environment
